import torch
import matplotlib.pyplot as plt

def show_tensor_images(images):
    '''
    Plots PVE, PVfree and GeneratedProjection by patch

    :param images: tensor of images of size (batch_size, 3,128,128)

    Each batch contains 3 images :  [0] Pojection with PVE from dataset
                                    [1] Projection WITHOUT PVE (PVfree) from dataset
                                    [2] Projection Generated by Pix2Pix
    :return: None
    '''

    images_unflat = images.detach().cpu()
    batch_size = images_unflat.shape[0]

    fig,ax = plt.subplots(3,batch_size, squeeze=False)

    for k in range(batch_size):
        maxc = torch.max(images_unflat[k,0:2,:,:])
        minc = torch.min(images_unflat[k,0:2,:,:])
        ax[0,k].imshow(images_unflat[k,0,:,:], vmin = minc, vmax= maxc)
        ax[0,k].set_title('PVE')
        ax[1,k].imshow(images_unflat[k,1,:,:], vmin = minc, vmax= maxc)
        ax[1, k].set_title('PVfree')
        ax[2,k].imshow(images_unflat[k,2,:,:])
        ax[2, k].set_title('FakePVfree')
    plt.show()

    # fig,ax = plt.subplots()
    # ax.plot(images_unflat[0,0,88,:], label = 'PVE')
    # ax.plot(images_unflat[0,1,88,:], label = 'PVfree')
    # ax.plot(images_unflat[0,2,88,:], label = 'PVC')
    # plt.legend()
    # plt.show()


def show_two_images(img_PVE, img_PVC):
    array_PVE = img_PVE.numpy()
    array_PVC = img_PVC.numpy()



    fig,ax = plt.subplots(1,2)
    im1 = ax[0].imshow(array_PVE[0,0,:,:], cmap = 'Greys')
    ax[0].set_title('Input PVE projection')
    im2 = ax[1].imshow(array_PVC[0,0,:,:], cmap = 'Greys')
    ax[1].set_title('Output PVC projection')

    fig.subplots_adjust(right=0.85)
    cbar_ax = fig.add_axes([0.88, 0.15, 0.04, 0.7])
    fig.colorbar(im2, cax=cbar_ax)


    plt.show()



def plot_losses(discriminator_losses,generator_losses):
    fig,ax1 = plt.subplots()

    p1 = ax1.plot(generator_losses, color = 'orange', label = 'Generator Loss')
    ax1.set_ylabel("Generator Loss", color = p1[0].get_color(), fontsize = 14)
    ax1.legend(loc=2) #upper left legend

    ax2 = ax1.twinx()
    p2 = ax2.plot(discriminator_losses,color = 'blue', label= 'Discriminator Loss')
    ax2.set_ylabel("Discriminator Loss", color = p2[0].get_color(),fontsize=14)
    ax2.legend(loc=1) #upper right legend

    ax2.set_xlabel('Iterations')
    ax2.set_title('Losses')

    plt.show()